apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-vault
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 8200
    protocol: TCP
    name: api
  - port: 8201
    protocol: TCP
    name: cluster-address
  selector:
    app: {{ .Release.Name }}-edgex-vault

