apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-kong
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: "tcp8000"
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: "admin"
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: "tcp8443"
    - port: 8444
      targetPort: 8444
      protocol: TCP
      name: "tcp8444"
  selector:
    app: {{ .Release.Name }}-edgex-kong
