apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-edgex-core-metadata
data:
  configuration.toml: |
    [Service]
    BootTimeout = 30000
    ClientMonitor = 15000
    CheckInterval = '10s'
    Host = '{{ .Release.Name }}-edgex-core-metadata'
    Port = 48081
    Protocol = 'http'
    ReadMaxLimit = 100
    StartupMsg = 'This is the EdgeX Core Metadata Microservice'
    Timeout = 5000

    [Registry]
    Host = '{{ .Release.Name }}-edgex-core-consul'
    Port = 8500
    Type = 'consul'

    [Logging]
    EnableRemote = false
    File = '/edgex/logs/edgex-core-metadata.log'

    [Clients]
      [Clients.Logging]
      Protocol = 'http'
      Host = '{{ .Release.Name }}-edgex-support-logging'
      Port = 48061
      [Clients.Notifications]
      Protocol = 'http'
      Host = '{{ .Release.Name }}-edgex-support-notifications'
      Port = 48060

    [Databases]
      [Databases.Primary]
      Host = '{{ .Release.Name }}-edgex-mongo'
      Name = 'metadata'
      Password = 'password'
      Port = 27017
      Username = 'meta'
      Timeout = 5000
      Type = 'mongodb'

    [Notifications]
      PostDeviceChanges = true
      Slug = 'device-change-'
      Content = 'Device update: '
      Sender = '{{ .Release.Name }}-edgex-core-metadata'
      Description = 'Metadata device notice'
      Label = 'metadata'