apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-core-metadata
  labels:
    app: edgex-core-metadata
spec:
  ports:
  - port: 48081
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-core-metadata