apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-support-scheduler
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  type: LoadBalancer
  ports:
  - port: 48085
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-support-scheduler
