apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-edgex-mongo
  labels:
    app: {{ .Release.Name }}-edgex
spec:
{{ if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.storageRequest }}