apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-mongo
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-mongo
