apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-core-command
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 48082
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-core-command
