apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-support-rulesengine
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 48075
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-support-rulesengine
