apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-ui
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-ui
