apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-edgex-support-logging
data:
  configuration.toml: |
    [Writable]
    Persistence = 'database'
    LogLevel = 'INFO'

    [Service]
    BootTimeout = 30000
    ClientMonitor = 15000
    CheckInterval = '10s'
    Host = '{{ .Release.Name }}-edgex-support-logging'
    Port = 48061
    Protocol = 'http'
    ReadMaxLimit = 100
    StartupMsg = 'This is the Support Logging Microservice'
    Timeout = 5000

    [Registry]
    Host = '{{ .Release.Name }}-edgex-core-consul'
    Port = 8500
    Type = 'consul'

    [Logging]
    File = '/edgex/logs/edgex-support-logging.log'

    [Databases]
      [Databases.Primary]
      Host = '{{ .Release.Name }}-edgex-mongo'
      Name = 'logging'
      Password = 'password'
      Port = 27017
      Username = 'logging'
      Timeout = 5000
      Type = 'mongodb'