apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-support-logging
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 48061
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-support-logging
