apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-edgex-kong-db
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-edgex-kong-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-edgex-kong-db
    spec:
      containers:
      - name: edgex-kong-db
        image: {{ .Values.image }}
        ports:
        - containerPort: 5432
          name: "tcp5432"
        env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
