apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-kong-db
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: "tcp5432"
  selector:
    app: {{ .Release.Name }}-edgex-kong-db
