apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-edgex-export-distro
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-edgex-export-distro
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-edgex-export-distro
    spec:
{{ if .Values.init_wait }}
      initContainers:
      - name: wait-svc-consul
        image: quay.io/stackanetes/kubernetes-entrypoint:v0.3.0
        env:
        - name: DEPENDENCY_SERVICE
          value: "edgex-core-consul,edgex-support-logging,edgex-export-client"
        - name: COMMAND
          value: "sleep 1"
{{ end }}
      containers:
      - name: edgex-export-distro
        image: {{ .Values.image }}
        ports:
        - containerPort: 48070
        #command: ["/bin/sh", "-c", "/export-distro"]
        command:
        {{ range .Values.command }}
        - {{ . }}
        {{ end }}
        volumeMounts:
        - name: export-distro-volume
          mountPath: /res/configuration.toml
          subPath: configuration.toml
      volumes:
      - name: export-distro-volume
        configMap:
          name:  {{ .Release.Name }}-edgex-export-distro
