apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-export-distro
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 48070
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-export-distro
