apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-edgex-export-client
data:
  configuration.toml: |
    [Writable]
    LogLevel = 'INFO'

    [Service]
    BootTimeout = 30000
    ClientMonitor = 15000
    CheckInterval = '10s'
    Host = '{{ .Release.Name }}-edgex-export-client'
    Port = 48071
    Protocol = 'http'
    ReadMaxLimit = 100
    StartupMsg = 'This is the Export Client Microservice'
    Timeout = 5000

    [Registry]
    Host = '{{ .Release.Name }}-edgex-core-consul'
    Port = 8500
    Type = 'consul'

    [Logging]
    EnableRemote = true
    File = '/edgex/logs/edgex-export-client.log'

    [Clients]
      [Clients.Distro]
      Protocol = 'http'
      Host = '{{ .Release.Name }}-edgex-export-distro'
      Port = 48070

      [Clients.Logging]
      Protocol = 'http'
      Host = '{{ .Release.Name }}-edgex-support-logging'
      Port = 48061

    [Databases]
      [Databases.Primary]
      Host = '{{ .Release.Name }}-edgex-mongo'
      Name = 'exportclient'
      Password = ''
      Port = 27017
      Username = ''
      Timeout = 5000
      Type = 'mongodb'
