apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-export-client
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 48071
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-export-client
