apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-edgex-support-notifications
data:
  configuration.toml: |
    [Writable]
    ResendLimit = 2
    LogLevel = 'INFO'

    [Service]
    BootTimeout = 30000
    ClientMonitor = 15000
    CheckInterval = '10s'
    Host = '{{ .Release.Name }}-edgex-support-notifications'
    Port = 48060
    Protocol = 'http'
    ReadMaxLimit = 1000
    StartupMsg = 'This is the Support Notifications Microservice'
    Timeout = 5000

    [Registry]
    Host = '{{ .Release.Name }}-edgex-core-consul'
    Port = 8500
    Type = 'consul'

    [Logging]
    EnableRemote = false
    File = '/edgex/logs/edgex-support-notifications.log'

    [Clients]
      [Clients.Logging]
      Protocol = 'http'
      Host = '{{ .Release.Name }}-edgex-support-logging'
      Port = 48061

    [Databases]
      [Databases.Primary]
      Host = '{{ .Release.Name }}-edgex-mongo'
      Name = 'notifications'
      Password = ''
      Port = 27017
      Username = ''
      Timeout = 5000
      Type = 'mongodb'

    [Smtp]
    Host = 'smtp.gmail.com'
    Password = 'mypassword'
    Port = 587
    Sender = 'jdoe@gmail.com'
    Subject = 'EdgeX Notification'
