# edingburgh release

#edgex core command subchart
edgex-core-command:
  enabled: true
  image: edgex/docker-core-command-go:1.0.1
  command: ["/core-command","--profile=docker","--confdir=/res"]
  init_wait: false

#edgex core data subchart
edgex-core-data:
  enabled: true
  image: edgexfoundry/docker-core-data-go:1.0.1
  command: ["/core-data", "--profile=docker","--confdir=/res"]

#edgex core metadata subchart
edgex-core-metadata:
  enabled: true
  image: edgexfoundry/docker-core-metadata-go:1.0.1
  command: ["/core-metadata","--profile=docker","--confdir=/res"]

#edgex export client subchart, depend on edgex-export-distro
edgex-export-client:
  enabled: true
  image: edgexfoundry/docker-export-client-go:1.0.1
  command: ["/export-client","--profile=docker","--confdir=/res"]

#edgex export distro
edgex-export-distro:
  enabled: false
  image: edgexfoundry/docker-export-distro-go:1.0.1
  command: ["/bin/sh", "-c", "/export-distro"]

#edgex mongodb subchart
edgex-mongo:
  enabled: true
  image: edgexfoundry/docker-edgex-mongo:1.0.1
  storage:
    #storageClassName: "false"
    storageRequest: "100Mi"

#edgex support logging subchart
edgex-support-logging:
  enabled: false
  image: edgexfoundry/docker-support-logging-go:1.0.1
  command: ["/support-logging","--profile=docker","--confdir=/res"]

#edgex support notifications subchart
edgex-support-notifications:
  enabled: false
  image: edgexfoundry/docker-support-notifications-go:1.0.1
  command: ["/support-notifications","--profile=docker","--confdir=/res"]

edgex-support-rulesengine:
  enabled: true
  image: edgexfoundry/docker-support-rulesengine:1.0.0
  command: ["/bin/sh", "-c", "java -jar -Djava.security.egd=file:/dev/urandom -Xmx100M $APP"]

edgex-support-scheduler:
  enabled: true
  image: edgexfoundry/docker-support-scheduler-go:1.0.1
  command: ["/support-scheduler","--profile=docker"]

edgex-ui-go:
  enabled: false
  image: edgexfoundry/docker-edgex-ui-go:1.0.0

edgex-device-virtual:
  enabled: false
  image: edgexfoundry/docker-device-virtual-go:1.0.0




