apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-device-virtual
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 49990
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-edgex-device-virtual
