apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-core-data
  labels:
    app: {{ .Release.Name }}-edgex
spec:
  ports:
  - port: 48080
    protocol: TCP
    name: "48080"
  - port: 5563
    protocol: TCP
    name: "5563"
  selector:
    app: {{ .Release.Name }}-edgex-core-data

